services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    group_add:
      - "993"
    ports:
      - 8096:8096
    deploy:
      resources:
        limits:
          memory: '4096M'
        reservations:
          memory: '2048M'
    volumes:
      - jellyfin-config:/config
      - type: bind
        source: /mnt/media
        target: /mnt/media
    restart: 'unless-stopped'
    devices:
      - /dev/dri/:/dev/dri/
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    deploy:
      resources:
        limits:
          memory: '1024M'
        reservations:
          memory: '512M'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-config:/config
      - /mnt/media:/mnt/media
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    deploy:
      resources:
        limits:
          memory: '1024M'
        reservations:
          memory: '512M'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - radarr-config:/config
      - /mnt/media:/mnt/media
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    deploy:
      resources:
        limits:
          memory: '1024M'
        reservations:
          memory: '512M'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarr-config:/config
      - /mnt/media:/mnt/media
    ports:
      - 8989:8989
    restart: unless-stopped
volumes:
  jellyfin-config:
    driver: local
  qbittorrent-config:
    driver: local
  radarr-config:
    driver: local
  sonarr-config:
    driver: local
