services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    group_add:
      - "993"
    ports:
      - 8096:8096
    deploy:
      resources:
        limits:
          memory: '4096M'
        reservations:
          memory: '2048M'
    volumes:
      - config:/config
      - type: bind
        source: /mnt/media
        target: /mnt/media
    restart: 'unless-stopped'
    devices:
      - /dev/dri/:/dev/dri/
volumes:
  config:
    driver: local
