services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    group_add:
      - "993"
    ports:
      - 8096:8096
    deploy:
      resources:
        limits:
          memory: '4096M'
        reservations:
          memory: '2048M'
    volumes:
      - jellyfin-config:/config
      - type: bind
        source: /mnt/media
        target: /mnt/media
    restart: 'unless-stopped'
    security_opt:
      - apparmor:unconfined
    # Disable hardware acceleration for now
    # devices:
    #   - /dev/dri/:/dev/dri/
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    deploy:
      resources:
        limits:
          memory: '1024M'
        reservations:
          memory: '512M'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-config:/config
      - /mnt/media:/mnt/media
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    deploy:
      resources:
        limits:
          memory: '1024M'
        reservations:
          memory: '512M'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - radarr-config:/config
      - /mnt/media:/mnt/media
    ports:
      - 7878:7878
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    deploy:
      resources:
        limits:
          memory: '1024M'
        reservations:
          memory: '512M'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarr-config:/config
      - /mnt/media:/mnt/media
    ports:
      - 8989:8989
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    deploy:
      resources:
        limits:
          memory: '1024M'
        reservations:
          memory: '512M'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - bazarr-config:/config
      - /mnt/media:/mnt/media
    ports:
      - 6767:6767
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    deploy:
      resources:
        limits:
          memory: '512M'
        reservations:
          memory: '256M'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true
    volumes:
      - jackett-config:/config
      - jackett-downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
volumes:
  jellyfin-config:
    driver: local
  qbittorrent-config:
    driver: local
  radarr-config:
    driver: local
  sonarr-config:
    driver: local
  bazarr-config:
    driver: local
  jackett-config:
    driver: local
  jackett-downloads:
    driver: local
