- hosts: all
  become: yes
  gather_facts: false
  collections:
    - community.docker

  tasks:
    - name: Wait for SSH to become available
      ansible.builtin.wait_for_connection:
        timeout: 300
        delay: 2

    - name: Gather facts
      ansible.builtin.setup:

    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
          - curl
          - intel-gpu-tools
        state: latest

    - name: Download Docker installation script
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0770'

    - name: Install Docker using the installation script
      ansible.builtin.shell: /tmp/get-docker.sh

    - name: Create media directory
      ansible.builtin.file:
        path: /opt/media
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy compose file
      ansible.builtin.copy:
        src: compose.yaml
        dest: /opt/media/compose.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Start Docker compose stack
      community.docker.docker_compose_v2:
        project_src: /opt/media/
        state: present
