- hosts: all
  become: yes

  tasks:
    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
          - curl
        state: latest
    
    - name: Download Docker installation script
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0770'
    
    - name: Install Docker using the installation script
      ansible.builtin.shell: /tmp/get-docker.sh
